# render.yaml
# This file defines the infrastructure for the Telegram Bot on Render.

# We use a Docker environment because we need to install system dependencies (ffmpeg, yt-dlp)
services:
  - type: web
    name: telegram-downloader-bot
    env: docker
    
    # Specify the location of the Dockerfile
    dockerContext: .
    dockerfilePath: Dockerfile

    # Environment Variables:
    # IMPORTANT: The real BOT_TOKEN must be set securely on the Render dashboard.
    envVars:
      - key: BOT_TOKEN
        value: YOUR_BOT_TOKEN_MUST_BE_SET_ON_RENDER
      - key: PORT
        value: 10000
        
    # Health check is crucial for keeping the service awake 24/7
    healthCheck:
      path: /health
      port: 10000
      interval: 10s
      timeout: 5s
      restartLimit: 3
