services:
  - type: web
    name: telegram-bot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    disk:
      name: downloads
      mountPath: /app/downloads
      sizeGB: 1
    envVars:
      - key: BOT_TOKEN
        sync: false
