services:
  - type: web
    name: telegram-bot
    env: go
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg wget python3 python3-pip
      pip3 install -U yt-dlp
      go build -o app .
    startCommand: ./app
    envVars:
      - key: PORT
        value: 10000
