services:
  - type: web
    name: uzdownloader-bot
    env: go
    plan: free
    region: frankfurt

    buildCommand: |
      apt-get update && \
      apt-get install -y ffmpeg python3 python3-pip && \
      pip install -U yt-dlp && \
      go build -o app .

    startCommand: ./app

    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: RENDER_EXTERNAL_URL
        value: uzdownloader-bot.onrender.com

    healthCheckPath: /healthz
    autoDeploy: true
